config/routes.rb
Rails.application.routes.draw do
  root 'welcome#index'
  get 'welcome/index'

  get 'session_new', to: 'sessions#new'
  post 'session_create', to: 'sessions#login'
  get 'session_destroy', to: 'sessions#logout'

  resources :players
  resources :matches do
    collection do
      get 'new_month', to: 'matches#new_month'
      post 'create_month', to: 'matches#create_month'
    end
  end
  resources :payments do
    collection do
      get 'new_match_payment', to: 'payments#new_match_payment'
      post 'create_match_payment', to: 'payments#create_match_payment'

      get 'new_month_payment', to: 'payments#new_month_payment'
      post 'create_month_payment', to: 'payments#create_month_payment'

      get 'new_credit', to: 'payments#new_credit'
      post 'create_credit', to: 'payments#create_credit'

      get 'new_debit', to: 'payments#new_debit'
      post 'create_debit', to: 'payments#create_debit'
    end
  end
end

app/models/payment.rb
# == Schema Information
#
# Table name: payments
#
#  id          :integer          not null, primary key
#  player_id   :integer
#  match_id    :integer
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#  value       :decimal(8, 2)
#  description :string
#

class Payment < ActiveRecord::Base
  belongs_to :match, optional: true
  belongs_to :player, optional: true

  with_options on: :create_credit do |v|
    v.validates_presence_of :description, :value
  end

  with_options on: :create_match_payment do |v|
    v.validates_presence_of :value, :match_id, :player_id
  end

  def self.pay_month(month_number, year, value, player)
    transaction do
      first_day = Date.new(year.to_i, month_number.to_i)
      last_day = (first_day + 1.months) - 1.days

      matches = (first_day..last_day).group_by(&:wday)[5]

      each_value = value.to_f / matches.count.to_f

      matches.each do |match|
        match_obj = Match.find_by_date(match)

        raise "some match may not exist!" unless match_obj

        payment = Payment.new match: match_obj, player: player, value: each_value, description: 'Mensal'
        payment.save!(context: :create_match_payment)
      end

      true
    end
  rescue
    false
  end

  def self.money_on_hand
    Payment.sum(:value)
  end
end

app/controllers/payments_controller.rb
class PaymentsController < ApplicationController
  before_action :authorize, except: :index

  def index
    @payments = Payment.all.order(id: :desc)
  end

  def new_match_payment
    @payment = Payment.new
  end

  def create_match_payment
    payment = Payment.new payment_params
    if payment.save(context: :create_match_payment)
      flash[:info] = "Você efetuou um pagamento com sucesso"
    else
      flash[:info] = "Erro: todos os campos precisam ser preenchidos."
    end

    redirect_to root_path
  end

  def new_month_payment
    @payment = Payment.new
  end

  def create_month_payment
    payments_params = params[:payments]
    player = Player.find(payments_params[:player_id])
    month_number = payments_params[:month_number]
    year = payments_params[:year]
    value = payments_params[:value]

    if Payment::pay_month(month_number, year, value, player)
      flash[:info] = "Pagamento mensal efetuado com sucesso"
      redirect_to payments_path
    else
      flash[:info] = "Ocorreu um erro"
      redirect_to payments_path
    end
  end

  def new_credit
    @payment = Payment.new
  end

  def create_credit
    payment = Payment.new payment_params
    if payment.save(context: :create_credit)
      flash[:info] = "Crédito adicionado"
      redirect_to payments_path
    else
      flash[:info] = "Ocorreu um erro"
      redirect_to payments_path
    end
  end

  def new_debit
    @payment = Payment.new
  end

  def create_debit
    negative_value = (params[:payment][:value].to_f * -1)
    description = params[:payment][:description]
    payment = Payment.new value: negative_value, description: description
    if payment.save(context: :create_credit)
      flash[:info] = "Crédito adicionado"
      redirect_to payments_path
    else
      flash[:info] = "Ocorreu um erro"
      redirect_to payments_path
    end
  end

  private

  def payment_params
    params.require(:payment).permit(:match_id, :player_id, :value, :description)
  end
end

app/views/payments/index.html.slim
.container
  p = "dinheiro em caixa: R$ #{Payment::money_on_hand}"
  = table_for(@payments, class: 'table table-striped') do |t|
    - t.column :player_id, label: 'Jogador' do |payment|
      = payment.player&.name
    - t.column :match_id, label: 'Partida' do |payment|
      = link_to payment.match.to_label, match_path(payment.match.id) if payment.match
    - t.column :value, label: 'Valor'
    - t.column :description, label: 'Descrição'

app/views/payments/new_credit.html.slim
.container
  .col-lg-offset-3.col-lg-5
    .alert.alert-success
      h3 style="margin-bottom: 25px;" Adicionar Crédito
      = simple_form_for @payment, url: create_credit_payments_path, method: :post  do |f|
        = f.input :value, label: 'Valor'
        = f.input :description, label: 'Descrição'

        = f.button :submit, "Salvar"

app/views/payments/new_debit.html.slim
.container
  .col-lg-offset-3.col-lg-5
    .alert.alert-success
      h3 style="margin-bottom: 25px;" Adicionar Débito
      = simple_form_for @payment, url: create_debit_payments_path, method: :post  do |f|
        = f.input :value, label: 'Valor'
        = f.input :description, label: 'Descrição'

        = f.button :submit, "Salvar"

app/views/payments/new_match_payment.html.slim
.container
  .col-lg-offset-3.col-lg-5
    .alert.alert-success
      h3 style="margin-bottom: 25px;" Criar Pagamento de Partida
      = simple_form_for @payment, url: create_match_payment_payments_path, method: :post  do |f|
        = f.input :player_id, label: 'Jogador', collection: Player.all
        = f.input :match_id, label: 'Partida', collection: Match.all.order(date: :desc), label_method: :to_label
        = f.input :value, label: 'Valor'
        = f.button :submit, "Salvar"

app/views/payments/new_month_payment.html.slim
.container
  .col-lg-offset-3.col-lg-5
    .alert.alert-success
      h3 style="margin-bottom: 25px;" Criar Pagamento de Mês
      = simple_form_for :payments, url: create_month_payment_payments_path, method: :post do |f|
        = f.input :player_id, label: 'Jogador', collection: Player.all
        = f.input :month_number, label: 'Número do mês', collection: 1..12, required: true
        = f.input :year
        = f.input :value, label: 'Valor'
        = f.button :submit, "Salvar"