config/routes.rb
Rails.application.routes.draw do
  root 'welcome#index'
  get 'welcome/index'

  get 'session_new', to: 'sessions#new'
  post 'session_create', to: 'sessions#login'
  get 'session_destroy', to: 'sessions#logout'

  resources :players
  resources :matches do
    collection do
      get 'new_month', to: 'matches#new_month'
      post 'create_month', to: 'matches#create_month'
    end
  end
  resources :payments do
    collection do
      get 'new_match_payment', to: 'payments#new_match_payment'
      post 'create_match_payment', to: 'payments#create_match_payment'

      get 'new_month_payment', to: 'payments#new_month_payment'
      post 'create_month_payment', to: 'payments#create_month_payment'

      get 'new_credit', to: 'payments#new_credit'
      post 'create_credit', to: 'payments#create_credit'

      get 'new_debit', to: 'payments#new_debit'
      post 'create_debit', to: 'payments#create_debit'
    end
  end
end

app/models/player.rb
# == Schema Information
#
# Table name: players
#
#  id         :integer          not null, primary key
#  name       :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Player < ActiveRecord::Base
  validates_presence_of :name
  validates_uniqueness_of :name

  has_many :payments
end

app/controllers/players_controller.rb
class PlayersController < ApplicationController
  before_action :authorize

  def index
    @players = Player.all
  end

  def new
    @player = Player.new
  end

  def create
    player = Player.new player_params
    if player.save
      flash[:info] = "Você criou jogadores com sucesso"
    else
      flash[:info] = "Erro: Nome precisa existir e ser diferente de qualquer outro."
    end

    redirect_to players_path
  end

  def edit
    @player = Player.find(params[:id])
  end

  def update
    @player = Player.find(params[:id])

    if @player.update player_params
      flash[:info] = "Você editou com sucesso"
    end

    redirect_to players_path
  end

  def destroy
    if Player.find(params[:id]).delete
      flash[:info] = "Você excluíu com sucesso"
    end

    redirect_to players_path
  end

  private

  def player_params
    params.require(:player).permit(:name)
  end
end

app/views/players/_form.html.slim
= simple_form_for @player do |f|
  = f.input :name, label: false, placeholder: 'Nome'
  = f.button :submit, "Salvar"

app/views/players/edit.html.slim
.container
  .col-lg-offset-3.col-lg-5
    .alert.alert-success
      h3 style="margin-bottom: 25px;" Editar jogador
      = render 'players/form'

app/views/players/index.html.slim
.container
  = table_for(@players, class: 'table table-striped') do |t|
    - t.column :name
    - t.column :actions do |player|
      = link_to 'Editar', edit_player_path(player.id), class: 'btn btn-xs btn-info', style: 'margin-right: 5px;'
      = link_to 'Excluir', player_path(player.id), class: 'btn btn-danger btn-xs', :method => :delete, :data => {:confirm => "Você tem certeza? "}
  = link_to 'Criar Jogador', new_player_path, class: 'btn btn-success'

app/views/players/new.html.slim
.container
  .col-lg-offset-3.col-lg-5
    .alert.alert-success
      h3 style="margin-bottom: 25px;" Criar jogador
      = render 'players/form'