config/routes.rb
Rails.application.routes.draw do
  root 'welcome#index'
  get 'welcome/index'

  get 'session_new', to: 'sessions#new'
  post 'session_create', to: 'sessions#login'
  get 'session_destroy', to: 'sessions#logout'

  resources :players
  resources :matches do
    collection do
      get 'new_month', to: 'matches#new_month'
      post 'create_month', to: 'matches#create_month'
    end
  end
  resources :payments do
    collection do
      get 'new_match_payment', to: 'payments#new_match_payment'
      post 'create_match_payment', to: 'payments#create_match_payment'

      get 'new_month_payment', to: 'payments#new_month_payment'
      post 'create_month_payment', to: 'payments#create_month_payment'

      get 'new_credit', to: 'payments#new_credit'
      post 'create_credit', to: 'payments#create_credit'

      get 'new_debit', to: 'payments#new_debit'
      post 'create_debit', to: 'payments#create_debit'
    end
  end
end

app/models/match.rb
# == Schema Information
#
# Table name: matches
#
#  id   :integer          not null, primary key
#  date :date
#

class Match < ActiveRecord::Base
  validates_presence_of :date
  validates_uniqueness_of :date

  has_many :payments

  def to_label
    self.date.strftime("%d/%m/%Y")
  end

  def can_be_deleted?
    !(payments.present?)
  end

  def get_all_fridays(month, next_year)
    year = Date.today.year

    year = Date.today.year + 1 if next_year != '0'

    first_day = Date.new(year, month.to_i)
    last_day = (first_day + 1.months) - 1.days

    (first_day..last_day).group_by(&:wday)[5]
  end

  def create_months_matches(month, next_year)
    dates = get_all_fridays(month, next_year)

    dates.each do |date|
      Match.create date: date
    end
  end
end

app/controllers/matches_controller.rb
class MatchesController < ApplicationController
  def index
    @matches = Match.all.order(date: :desc).paginate(page: params[:page], per_page: 10)
  end

  def show
    @match = Match.find(params[:id])
  end

  def new
    @match = Match.new
  end

  def create
    match = Match.new matches_params
    if match.save
      flash[:info] = "Você criou uma partida com sucesso"
    else
      flash[:info] = "Erro: Já existe uma partida com esta data."
    end

    redirect_to matches_path
  end

  def edit
    @match = Match.find(params[:id])
  end

  def update
    @match = Match.find(params[:id])

    if @match.update matches_params
      flash[:info] = "Você editou com sucesso"
    end

    redirect_to matches_path
  end

  def destroy
    if Match.find(params[:id]).delete
      flash[:info] = "Você excluíu com sucesso"
    end

    redirect_to matches_path
  end

  def new_month
  end

  def create_month
    Match.new.create_months_matches(params[:match][:month_number], params[:match][:next_year]) if params[:match][:month_number].present?

    flash[:info] = "Criado partidas com sucesso"
    redirect_to matches_path
  end

  private

  def matches_params
    params.require(:match).permit(:date)
  end
end

app/views/matches/_form.html.slim
= simple_form_for @match do |f|
  = f.input :date, label: false, placeholder: 'Data', as: :date
  = f.button :submit, "Salvar"

app/views/matches/edit.html.slim
.container
  .col-lg-offset-3.col-lg-5
    .alert.alert-success
      h3 style="margin-bottom: 25px;" Editar partida
      = render 'matches/form'

app/views/matches/index.html.slim
.container
  = table_for(@matches, class: 'table table-striped') do |t|
    - t.column :date do |match|
      = date_format(match.date)
    - if logged_in?
      - t.column :actions do |match|
        = link_to 'Ver', match_path(match.id), class: 'btn btn-xs btn-success', style: 'margin-right: 5px;'
        - if match.can_be_deleted?
          = link_to 'Editar', edit_match_path(match.id), class: 'btn btn-xs btn-info', style: 'margin-right: 5px;'
          = link_to 'Excluir', match_path(match.id), class: 'btn btn-danger btn-xs', :method => :delete, :data => {:confirm => "Você tem certeza? "}
  .row.pull-right
    = will_paginate @matches
  .row
    .action-buttons
      = link_to 'Criar Partida', new_match_path, class: 'btn btn-success' if logged_in?
      = link_to 'Criar Todas Partidas de Mês', new_month_matches_path, class: 'btn btn-success' if logged_in?

app/views/matches/new.html.slim
.container
  .col-lg-offset-3.col-lg-5
    .alert.alert-success
      h3 style="margin-bottom: 25px;" Criar partida
      = render 'matches/form'

app/views/matches/new_month.html.slim
.container
  .col-lg-offset-3.col-lg-5
    .alert.alert-success
      h3 style="margin-bottom: 25px;" Criar partida
      = simple_form_for :match, url: create_month_matches_path, method: :post do |f|
        = f.input :month_number, label: 'Número do mês', collection: 1..12, required: true
        = f.input :next_year, label: 'Do próximo ano', as: :boolean
        = f.button :submit, "Salvar"

app/views/matches/show.html.slim
.container
  .row
    .page-header
      h2 = date_format(@match.date)
  .row
    h3 Pagamentos
    = table_for(@match.payments, class: 'table table-striped') do |t|
      - t.column :player_id, label: 'Jogador' do |payment|
        = payment.player.name
      - t.column :value, label: 'Valor'
      - t.column :description, label: 'Descrição'