config/routes.rb
Rails.application.routes.draw do
  root 'welcome#index'
  get 'welcome/index'

  get 'session_new', to: 'sessions#new'
  post 'session_create', to: 'sessions#login'
  get 'session_destroy', to: 'sessions#logout'

  resources :players
  resources :matches do
    collection do
      get 'new_month', to: 'matches#new_month'
      post 'create_month', to: 'matches#create_month'
    end
  end
  resources :payments do
    collection do
      get 'new_match_payment', to: 'payments#new_match_payment'
      post 'create_match_payment', to: 'payments#create_match_payment'

      get 'new_month_payment', to: 'payments#new_month_payment'
      post 'create_month_payment', to: 'payments#create_month_payment'

      get 'new_credit', to: 'payments#new_credit'
      post 'create_credit', to: 'payments#create_credit'

      get 'new_debit', to: 'payments#new_debit'
      post 'create_debit', to: 'payments#create_debit'
    end
  end
end

app/helpers/layout_helper.rb
require 'builder'

module LayoutHelper
  # Monta uma tag <span> com atributos +data+ preparados para montar um componente React.
  #
  # @param [String] name o nome do componente React
  # @param [Object] props as propriedades
  def react_component(name, props = {}, &block)
    content_tag(:span, nil, data: { react_class: name, react_props: props }, &block)
  end
end

app/views/layouts/_header.html.slim
nav.navbar.navbar-default
  .container-fluid
    /! Brand and toggle get grouped for better mobile display
    .navbar-header
      button.navbar-toggle.collapsed aria-expanded="false" data-target="#bs-example-navbar-collapse-1" data-toggle="collapse" type="button" 
        span.sr-only Toggle navigation
        span.icon-bar
        span.icon-bar
        span.icon-bar
      a.navbar-brand href="#"  Portal Transparência Futebol Zallpy
    /! Collect the nav links, forms, and other content for toggling
    #bs-example-navbar-collapse-1.collapse.navbar-collapse
      ul.nav.navbar-nav
        li = link_to 'Partidas', matches_path
        li = link_to 'Fluxo de caixa', payments_path
        - if logged_in?
          li = link_to 'Jogadores', players_path
          li.dropdown
            a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"
              | Pagamentos
              span class="caret"
            ul.dropdown-menu
              li = link_to 'Efetuar pagamento de partida', new_match_payment_payments_path
              li = link_to 'Efetuar pagamento mensal', new_month_payment_payments_path
              li = link_to 'Adicionar crédito', new_credit_payments_path
              li = link_to 'Aplicar debito', new_debit_payments_path
      ul.nav.navbar-nav.navbar-right
        - if logged_in?
          p.navbar-text = "Logado como: #{current_user.name}"
          li = link_to 'logout', session_destroy_path
        - else
          li = link_to 'login', session_new_path

app/views/layouts/application.html.slim
doctype html
html
  head
    title PortalTransparencia
    = csrf_meta_tags

    = javascript_include_tag 'vendor'
    = javascript_include_tag 'app'
  body
    = render "layouts/header"
    .container
      = flash_messages
    = yield